name: Auto-update MAC Portal

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *' # Otomatis berjalan setiap 6 jam sekali

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Updater Script
      run: python update_portal.py

    - name: Commit and Push Changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add *.m3u || true
        git commit -m "Auto-update playlist channels" || true
        git push || true
